// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/system/system.proto

package go_micro_srv_system

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_e32c6089d0d6c327, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ConfRequest struct {
	RpcPort              int64    `protobuf:"varint,1,opt,name=rpcPort,proto3" json:"rpcPort,omitempty"`
	MnKey                string   `protobuf:"bytes,2,opt,name=mnKey,proto3" json:"mnKey,omitempty"`
	ExternalIp           string   `protobuf:"bytes,3,opt,name=externalIp,proto3" json:"externalIp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfRequest) Reset()         { *m = ConfRequest{} }
func (m *ConfRequest) String() string { return proto.CompactTextString(m) }
func (*ConfRequest) ProtoMessage()    {}
func (*ConfRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e32c6089d0d6c327, []int{1}
}

func (m *ConfRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfRequest.Unmarshal(m, b)
}
func (m *ConfRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfRequest.Marshal(b, m, deterministic)
}
func (m *ConfRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfRequest.Merge(m, src)
}
func (m *ConfRequest) XXX_Size() int {
	return xxx_messageInfo_ConfRequest.Size(m)
}
func (m *ConfRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfRequest proto.InternalMessageInfo

func (m *ConfRequest) GetRpcPort() int64 {
	if m != nil {
		return m.RpcPort
	}
	return 0
}

func (m *ConfRequest) GetMnKey() string {
	if m != nil {
		return m.MnKey
	}
	return ""
}

func (m *ConfRequest) GetExternalIp() string {
	if m != nil {
		return m.ExternalIp
	}
	return ""
}

type Response struct {
	Errno                string   `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_e32c6089d0d6c327, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *Response) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type SysResponse struct {
	Errno                string   `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	CpuPercent           float32  `protobuf:"fixed32,3,opt,name=CpuPercent,proto3" json:"CpuPercent,omitempty"`
	MemPercent           float32  `protobuf:"fixed32,4,opt,name=MemPercent,proto3" json:"MemPercent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SysResponse) Reset()         { *m = SysResponse{} }
func (m *SysResponse) String() string { return proto.CompactTextString(m) }
func (*SysResponse) ProtoMessage()    {}
func (*SysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e32c6089d0d6c327, []int{3}
}

func (m *SysResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysResponse.Unmarshal(m, b)
}
func (m *SysResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysResponse.Marshal(b, m, deterministic)
}
func (m *SysResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysResponse.Merge(m, src)
}
func (m *SysResponse) XXX_Size() int {
	return xxx_messageInfo_SysResponse.Size(m)
}
func (m *SysResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SysResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SysResponse proto.InternalMessageInfo

func (m *SysResponse) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *SysResponse) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *SysResponse) GetCpuPercent() float32 {
	if m != nil {
		return m.CpuPercent
	}
	return 0
}

func (m *SysResponse) GetMemPercent() float32 {
	if m != nil {
		return m.MemPercent
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.system.Request")
	proto.RegisterType((*ConfRequest)(nil), "go.micro.srv.system.ConfRequest")
	proto.RegisterType((*Response)(nil), "go.micro.srv.system.Response")
	proto.RegisterType((*SysResponse)(nil), "go.micro.srv.system.SysResponse")
}

func init() { proto.RegisterFile("proto/system/system.proto", fileDescriptor_e32c6089d0d6c327) }

var fileDescriptor_e32c6089d0d6c327 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0xb5, 0x4d, 0x4d, 0xed, 0xd4, 0x83, 0x8c, 0x22, 0xb1, 0xd8, 0x52, 0x72, 0xf2, 0xb4, 0x82,
	0x7e, 0x42, 0x0f, 0xa2, 0xa2, 0x84, 0xe4, 0xe0, 0xc9, 0x43, 0x0c, 0x63, 0x29, 0xb8, 0xbb, 0x71,
	0x76, 0x23, 0x06, 0xff, 0xc8, 0xaf, 0x94, 0x6c, 0x36, 0x98, 0x43, 0xbc, 0x78, 0xca, 0xbc, 0xf7,
	0x66, 0xde, 0x90, 0x37, 0x0b, 0x67, 0x25, 0x6b, 0xab, 0x2f, 0x4d, 0x6d, 0x2c, 0x49, 0xff, 0x11,
	0x8e, 0xc3, 0xe3, 0xad, 0x16, 0x72, 0x57, 0xb0, 0x16, 0x86, 0x3f, 0x44, 0x2b, 0xc5, 0x4b, 0x98,
	0xa6, 0xf4, 0x5e, 0x91, 0xb1, 0x88, 0x30, 0x51, 0xb9, 0xa4, 0x68, 0xb4, 0x1e, 0x5d, 0xcc, 0x52,
	0x57, 0xc7, 0xcf, 0x30, 0xdf, 0x68, 0xf5, 0xda, 0xb5, 0x44, 0x30, 0xe5, 0xb2, 0x48, 0x34, 0x5b,
	0xd7, 0x15, 0xa4, 0x1d, 0xc4, 0x13, 0xd8, 0x97, 0xea, 0x9e, 0xea, 0x68, 0xec, 0xa6, 0x5b, 0x80,
	0x2b, 0x00, 0xfa, 0xb4, 0xc4, 0x2a, 0x7f, 0xbb, 0x2d, 0xa3, 0xc0, 0x49, 0x3d, 0x26, 0xbe, 0x83,
	0x83, 0x94, 0x4c, 0xa9, 0x95, 0xa1, 0xc6, 0x81, 0x98, 0x95, 0xf6, 0xfb, 0x5b, 0x80, 0xa7, 0x10,
	0x12, 0xb3, 0x34, 0x5b, 0x6f, 0xec, 0x11, 0x1e, 0x41, 0xd0, 0x90, 0xad, 0x65, 0x53, 0xc6, 0x5f,
	0x30, 0xcf, 0x6a, 0xf3, 0x4f, 0xbb, 0x15, 0xc0, 0xa6, 0xac, 0x12, 0xe2, 0x82, 0x94, 0x75, 0xae,
	0xe3, 0xb4, 0xc7, 0x34, 0xfa, 0x03, 0xc9, 0x4e, 0x9f, 0xb4, 0xfa, 0x2f, 0x73, 0xf5, 0x3d, 0x82,
	0x30, 0x73, 0x89, 0x62, 0x02, 0x87, 0x37, 0x64, 0xb3, 0xda, 0x64, 0x36, 0xb7, 0x95, 0xc1, 0x73,
	0x31, 0x90, 0xbb, 0xf0, 0x89, 0x2e, 0xd6, 0x83, 0x6a, 0xef, 0x47, 0xe2, 0x3d, 0x7c, 0x84, 0xd9,
	0x13, 0xef, 0x2c, 0x35, 0x97, 0xc0, 0xe1, 0x81, 0xde, 0x91, 0x16, 0xcb, 0x3f, 0x16, 0x76, 0x7e,
	0x2f, 0xa1, 0x7b, 0x0f, 0xd7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7d, 0x63, 0x8d, 0x45, 0x2c,
	0x02, 0x00, 0x00,
}
